dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: D7e55xOWi0ILoJrKlbhiNvY4ZDPMP3l2etYO7W9sinv8tYG0E4No8FVYIhuaTPk629RWIbS2WJgCgPOdy1GxL6FEcLB8+7XXKU8oXs929M7+m8bE0dq5ImGymSoDydJz/pGGx6KOTRkoquqJWk7Gq/m2x44+rKN+f1/RccmJl3OLv9tyG8cXfANZogKBOjSieTjRcq9cTKKKkyhV4RRykL3TQo3PwYbQnCHh0g3VkZpuDIrH8sFN5DArtOE9TTZrnExBL9h3HSK9tb2PgCRyDSWbxqsKpt7/EnPJc1LzZDbJnuEadnvQqaN6lP7bUZ8sB88iSSZtqT+l9GJnPdeWd9eeJriCzMetgqcWH1/hJiVyhKnPdejRLo+w6Y3fAurXkwDetjD9lSMHtSOAW2SjIfytRh4EOJRCG6VEP+xP6xihNYWOqQYmTULO8/FV8BuuzUj+NsFXt4Hi4TtpkVWMIzAj88PuBCYxu/JIq61yLv8WgySbEB5P6AXputziAC1WEJwziuabMzEfEeNjq3/8Sjk4KiK74EYr8pMzACFLkEhumJmbJfvRzhRDgLNpyqVIGtDoZ9oXwttMgREhu9xKiyzm1I4nxlkOpA7lgnJhxbyxamChX9LoWARWA20Cx4AInpM09ZjpQVEBpxXKK790eO4OtQDWgXLl3RaRZ4hVYSQ=
