global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#egor_petrov'
